from core.name_convention import *

test_set_fruits = [FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_5, ID.ID_3, CameraType.VIS),
                   FruitRecord(Fruit.AVOCADO, Side.BACK,
                               Day.DAY_M2_3, ID.ID_52, CameraType.VIS),
                   FruitRecord(Fruit.AVOCADO, Side.BACK,
                               Day.DAY_M2_2, ID.ID_33, CameraType.VIS),
                   FruitRecord(Fruit.AVOCADO, Side.FRONT,
                               Day.DAY_5, ID.ID_3, CameraType.VIS),
                   FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_5,
                               ID.ID_23, CameraType.VIS),
                   FruitRecord(Fruit.AVOCADO, Side.BACK,
                               Day.DAY_M2_4, ID.ID_43, CameraType.VIS),
                   FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_6,
                               ID.ID_25, CameraType.VIS),
                   FruitRecord(Fruit.AVOCADO, Side.FRONT,
                               Day.DAY_6, ID.ID_6, CameraType.VIS),
                   FruitRecord(Fruit.AVOCADO, Side.BACK,
                               Day.DAY_M2_7, ID.ID_45, CameraType.VIS),
                   FruitRecord(Fruit.AVOCADO, Side.BACK,
                               Day.DAY_7, ID.ID_2, CameraType.VIS),
                   FruitRecord(Fruit.AVOCADO, Side.FRONT,
                               Day.DAY_M2_10, ID.ID_44, CameraType.VIS),
                   FruitRecord(Fruit.AVOCADO, Side.FRONT,
                               Day.DAY_9, ID.ID_22, CameraType.VIS),
                   FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_9,
                               ID.ID_22, CameraType.VIS),
                   FruitRecord(Fruit.AVOCADO, Side.BACK,
                               Day.DAY_M2_6, ID.ID_46, CameraType.VIS),
                   FruitRecord(Fruit.AVOCADO, Side.FRONT,
                               Day.DAY_10, ID.ID_7, CameraType.VIS),
                   FruitRecord(Fruit.AVOCADO, Side.BACK,
                               Day.DAY_5, ID.ID_3, CameraType.NIR),
                   FruitRecord(Fruit.AVOCADO, Side.FRONT,
                               Day.DAY_3, ID.ID_13, CameraType.NIR),
                   FruitRecord(Fruit.AVOCADO, Side.FRONT,
                               Day.DAY_5, ID.ID_3, CameraType.NIR),
                   FruitRecord(Fruit.AVOCADO, Side.BACK,
                               Day.DAY_3, ID.ID_5, CameraType.NIR),
                   FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_7,
                               ID.ID_27, CameraType.NIR),
                   FruitRecord(Fruit.AVOCADO, Side.FRONT,
                               Day.DAY_6, ID.ID_19, CameraType.NIR),
                   FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_8,
                               ID.ID_10, CameraType.NIR),
                   FruitRecord(Fruit.AVOCADO, Side.FRONT,
                               Day.DAY_8, ID.ID_28, CameraType.NIR),
                   FruitRecord(Fruit.AVOCADO, Side.FRONT,
                               Day.DAY_10, ID.ID_7, CameraType.NIR),
                   FruitRecord(Fruit.KIWI, Side.BACK, Day.DAY_M2_12,
                               ID.ID_76, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.FRONT, Day.DAY_M2_5,
                               ID.ID_51, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.BACK, Day.DAY_5,
                               ID.ID_26, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.BACK, Day.DAY_5,
                               ID.ID_32, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.BACK, Day.DAY_4,
                               ID.ID_18, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.BACK, Day.DAY_M2_10,
                               ID.ID_55, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.FRONT,
                               Day.DAY_M2_10, ID.ID_46, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.BACK, Day.DAY_M2_1,
                               ID.ID_71, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.BACK, Day.DAY_M2_11,
                               ID.ID_73, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.FRONT, Day.DAY_6,
                               ID.ID_36, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.FRONT,
                               Day.DAY_M2_16, ID.ID_57, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.FRONT, Day.DAY_4,
                               ID.ID_29, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.BACK, Day.DAY_6,
                               ID.ID_11, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.FRONT, Day.DAY_5,
                               ID.ID_5, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.BACK, Day.DAY_M2_16,
                               ID.ID_50, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.BACK, Day.DAY_3,
                               ID.ID_23, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.FRONT, Day.DAY_4,
                               ID.ID_13, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.BACK, Day.DAY_M2_16,
                               ID.ID_48, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.BACK, Day.DAY_M2_11,
                               ID.ID_68, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.FRONT,
                               Day.DAY_M2_15, ID.ID_45, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.FRONT, Day.DAY_M2_8,
                               ID.ID_63, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.BACK, Day.DAY_4,
                               ID.ID_13, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.BACK, Day.DAY_6,
                               ID.ID_20, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.BACK, Day.DAY_7,
                               ID.ID_16, CameraType.VIS),
                   FruitRecord(Fruit.KIWI, Side.BACK, Day.DAY_7,
                               ID.ID_24, CameraType.NIR),
                   FruitRecord(Fruit.KIWI, Side.FRONT, Day.DAY_5,
                               ID.ID_26, CameraType.NIR),
                   FruitRecord(Fruit.KIWI, Side.FRONT, Day.DAY_5,
                               ID.ID_32, CameraType.NIR),
                   FruitRecord(Fruit.KIWI, Side.BACK, Day.DAY_5,
                               ID.ID_8, CameraType.NIR),
                   FruitRecord(Fruit.KIWI, Side.FRONT, Day.DAY_5,
                               ID.ID_2, CameraType.NIR),
                   FruitRecord(Fruit.KIWI, Side.BACK, Day.DAY_4,
                               ID.ID_12, CameraType.NIR),
                   FruitRecord(Fruit.KIWI, Side.FRONT, Day.DAY_3,
                               ID.ID_7, CameraType.NIR),
                   FruitRecord(Fruit.KIWI, Side.BACK, Day.DAY_10,
                               ID.ID_27, CameraType.NIR),
                   FruitRecord(Fruit.KIWI, Side.FRONT, Day.DAY_10, ID.ID_27,
                               CameraType.NIR)] \
                  + [FruitRecord(Fruit.KAKI, Side.BACK, Day.DAY_M3_5, ID.ID_26, CameraType.VIS), FruitRecord(Fruit.KAKI, Side.FRONT, Day.DAY_M3_2, ID.ID_3, CameraType.VIS), FruitRecord(Fruit.KAKI, Side.BACK, Day.DAY_M3_2, ID.ID_3, CameraType.VIS), FruitRecord(Fruit.KAKI, Side.BACK, Day.DAY_M3_2, ID.ID_1, CameraType.VIS), FruitRecord(Fruit.KAKI, Side.BACK, Day.DAY_M3_7, ID.ID_27, CameraType.VIS), FruitRecord(Fruit.KAKI, Side.FRONT, Day.DAY_M3_7, ID.ID_37, CameraType.VIS), FruitRecord(Fruit.KAKI, Side.BACK, Day.DAY_M3_9, ID.ID_32, CameraType.VIS), FruitRecord(Fruit.KAKI, Side.FRONT, Day.DAY_M3_4, ID.ID_14, CameraType.VIS), FruitRecord(Fruit.KAKI, Side.FRONT, Day.DAY_M3_7, ID.ID_23, CameraType.VIS), FruitRecord(Fruit.KAKI, Side.BACK, Day.DAY_M3_4, ID.ID_7, CameraType.VIS), FruitRecord(Fruit.KAKI, Side.BACK, Day.DAY_M3_3, ID.ID_10, CameraType.VIS), FruitRecord(Fruit.KAKI, Side.FRONT, Day.DAY_M3_7, ID.ID_39, CameraType.VIS), FruitRecord(Fruit.KAKI, Side.BACK, Day.DAY_M3_4, ID.ID_30, CameraType.VIS_COR), FruitRecord(Fruit.KAKI, Side.FRONT, Day.DAY_M3_4, ID.ID_30, CameraType.VIS_COR), FruitRecord(Fruit.KAKI, Side.BACK, Day.DAY_M3_5, ID.ID_26, CameraType.VIS_COR), FruitRecord(Fruit.KAKI, Side.BACK, Day.DAY_M3_2, ID.ID_3, CameraType.VIS_COR), FruitRecord(Fruit.KAKI, Side.FRONT, Day.DAY_M3_4, ID.ID_14, CameraType.VIS_COR), FruitRecord(Fruit.KAKI, Side.BACK, Day.DAY_M3_9, ID.ID_25, CameraType.VIS_COR), FruitRecord(Fruit.KAKI, Side.BACK, Day.DAY_M3_2, ID.ID_21, CameraType.VIS_COR), FruitRecord(Fruit.KAKI, Side.FRONT, Day.DAY_M3_5, ID.ID_13, CameraType.VIS_COR), FruitRecord(Fruit.KAKI, Side.FRONT, Day.DAY_M3_9, ID.ID_4, CameraType.VIS_COR), FruitRecord(Fruit.KAKI, Side.FRONT, Day.DAY_M3_4, ID.ID_7, CameraType.VIS_COR), FruitRecord(Fruit.KAKI, Side.FRONT, Day.DAY_M3_7, ID.ID_39, CameraType.VIS_COR), FruitRecord(Fruit.KAKI, Side.FRONT, Day.DAY_M3_8, ID.ID_22, CameraType.VIS_COR), FruitRecord(Fruit.MANGO, Side.FRONT, Day.DAY_M3_9, ID.ID_4, CameraType.VIS), FruitRecord(Fruit.MANGO, Side.FRONT, Day.DAY_M3_11, ID.ID_38, CameraType.VIS), FruitRecord(Fruit.MANGO, Side.BACK, Day.DAY_M3_5, ID.ID_13, CameraType.VIS), FruitRecord(Fruit.MANGO, Side.FRONT, Day.DAY_M3_9, ID.ID_34, CameraType.VIS), FruitRecord(Fruit.MANGO, Side.FRONT, Day.DAY_M3_7, ID.ID_37, CameraType.VIS), FruitRecord(Fruit.MANGO, Side.BACK, Day.DAY_M3_1, ID.ID_19, CameraType.VIS), FruitRecord(Fruit.MANGO, Side.FRONT, Day.DAY_M3_10, ID.ID_12, CameraType.VIS), FruitRecord(Fruit.MANGO, Side.BACK, Day.DAY_M3_7, ID.ID_23, CameraType.VIS), FruitRecord(Fruit.MANGO, Side.BACK, Day.DAY_M3_12, ID.ID_30, CameraType.VIS), FruitRecord(Fruit.MANGO, Side.BACK, Day.DAY_M3_12, ID.ID_14, CameraType.VIS), FruitRecord(Fruit.MANGO, Side.BACK, Day.DAY_M3_12, ID.ID_31, CameraType.VIS), FruitRecord(Fruit.MANGO, Side.FRONT, Day.DAY_M3_12, ID.ID_30, CameraType.VIS), FruitRecord(Fruit.MANGO, Side.BACK, Day.DAY_M3_7, ID.ID_29, CameraType.VIS_COR), FruitRecord(Fruit.MANGO, Side.BACK, Day.DAY_M3_7, ID.ID_27, CameraType.VIS_COR), FruitRecord(Fruit.MANGO, Side.BACK, Day.DAY_M3_8, ID.ID_22, CameraType.VIS_COR), FruitRecord(Fruit.MANGO, Side.BACK, Day.DAY_M3_9, ID.ID_4, CameraType.VIS_COR), FruitRecord(Fruit.MANGO, Side.FRONT, Day.DAY_M3_7, ID.ID_37, CameraType.VIS_COR), FruitRecord(Fruit.MANGO, Side.BACK, Day.DAY_M3_9, ID.ID_25, CameraType.VIS_COR), FruitRecord(Fruit.MANGO, Side.FRONT, Day.DAY_M3_11, ID.ID_28, CameraType.VIS_COR), FruitRecord(Fruit.MANGO, Side.BACK, Day.DAY_M3_7, ID.ID_23, CameraType.VIS_COR), FruitRecord(Fruit.MANGO, Side.BACK, Day.DAY_M3_4, ID.ID_20, CameraType.VIS_COR), FruitRecord(Fruit.MANGO, Side.BACK, Day.DAY_M3_12, ID.ID_35, CameraType.VIS_COR), FruitRecord(Fruit.MANGO, Side.FRONT, Day.DAY_M3_4, ID.ID_20, CameraType.VIS_COR), FruitRecord(Fruit.MANGO, Side.FRONT, Day.DAY_M3_10, ID.ID_40, CameraType.VIS_COR)] \
                  + [FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_5, ID.ID_33, CameraType.VIS), FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_5, ID.ID_32, CameraType.VIS), FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_5, ID.ID_34, CameraType.VIS), FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_9, ID.ID_4, CameraType.VIS), FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_2, ID.ID_23, CameraType.VIS), FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_3, ID.ID_28, CameraType.VIS), FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_9, ID.ID_21, CameraType.VIS), FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_9, ID.ID_21, CameraType.VIS), FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_8, ID.ID_10, CameraType.VIS), FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_5, ID.ID_33, CameraType.VIS_COR), FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_5, ID.ID_31, CameraType.VIS_COR), FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_5, ID.ID_32, CameraType.VIS_COR), FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_4, ID.ID_14, CameraType.VIS_COR), FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_3, ID.ID_8, CameraType.VIS_COR), FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_2, ID.ID_17, CameraType.VIS_COR), FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_7, ID.ID_24, CameraType.VIS_COR), FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_9, ID.ID_21, CameraType.VIS_COR), FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_6, ID.ID_25, CameraType.VIS_COR), FruitRecord(Fruit.PAPAYA, Side.FRONT, Day.DAY_M4_4, ID.ID_23, CameraType.VIS), FruitRecord(Fruit.PAPAYA, Side.BACK, Day.DAY_M4_1, ID.ID_19, CameraType.VIS), FruitRecord(Fruit.PAPAYA, Side.BACK, Day.DAY_M4_4, ID.ID_15, CameraType.VIS), FruitRecord(Fruit.PAPAYA, Side.BACK, Day.DAY_M4_7, ID.ID_1, CameraType.VIS), FruitRecord(Fruit.PAPAYA, Side.BACK, Day.DAY_M4_3, ID.ID_5, CameraType.VIS), FruitRecord(Fruit.PAPAYA, Side.FRONT, Day.DAY_M4_5, ID.ID_11, CameraType.VIS), FruitRecord(Fruit.PAPAYA, Side.BACK, Day.DAY_M4_7, ID.ID_22, CameraType.VIS), FruitRecord(Fruit.PAPAYA, Side.FRONT, Day.DAY_M4_7, ID.ID_25, CameraType.VIS), FruitRecord(Fruit.PAPAYA, Side.BACK, Day.DAY_M4_7, ID.ID_25, CameraType.VIS), FruitRecord(Fruit.PAPAYA, Side.BACK, Day.DAY_M4_4, ID.ID_23, CameraType.VIS_COR), FruitRecord(Fruit.PAPAYA, Side.BACK, Day.DAY_M4_1, ID.ID_19, CameraType.VIS_COR), FruitRecord(Fruit.PAPAYA, Side.BACK, Day.DAY_M4_1, ID.ID_20, CameraType.VIS_COR), FruitRecord(Fruit.PAPAYA, Side.BACK, Day.DAY_M4_4, ID.ID_28, CameraType.VIS_COR), FruitRecord(Fruit.PAPAYA, Side.BACK, Day.DAY_M4_6, ID.ID_14, CameraType.VIS_COR), FruitRecord(Fruit.PAPAYA, Side.BACK, Day.DAY_M4_6, ID.ID_6, CameraType.VIS_COR), FruitRecord(Fruit.PAPAYA, Side.BACK, Day.DAY_M4_7, ID.ID_22, CameraType.VIS_COR), FruitRecord(Fruit.PAPAYA, Side.FRONT, Day.DAY_M4_7, ID.ID_22, CameraType.VIS_COR), FruitRecord(Fruit.PAPAYA, Side.BACK, Day.DAY_M4_6, ID.ID_24, CameraType.VIS_COR)]\
                  + [FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_1, ID.ID_22, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_1, ID.ID_22, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_1, ID.ID_22, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_1, ID.ID_22, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_1, ID.ID_29, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_1, ID.ID_29, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_1, ID.ID_29, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_1, ID.ID_29, CameraType.VIS),
                                       FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_2, ID.ID_17, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_2, ID.ID_17, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_2, ID.ID_17, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_2, ID.ID_17, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_2, ID.ID_18, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_2, ID.ID_18, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_2, ID.ID_18, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_2, ID.ID_18, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_2, ID.ID_23, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_2, ID.ID_23, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_2, ID.ID_23, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_2, ID.ID_23, CameraType.VIS),
                                       FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_3, ID.ID_2, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_3, ID.ID_2, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_3, ID.ID_2, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_3, ID.ID_2, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_3, ID.ID_6, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_3, ID.ID_6, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_3, ID.ID_6, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_3, ID.ID_6, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_3, ID.ID_8, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_3, ID.ID_8, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_3, ID.ID_8, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_3, ID.ID_8, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_3, ID.ID_28, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_3, ID.ID_28, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_3, ID.ID_28, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_3, ID.ID_28, CameraType.VIS),
                                       FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_4, ID.ID_7, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_4, ID.ID_7, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_4, ID.ID_7, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_4, ID.ID_7, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_4, ID.ID_13, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_4, ID.ID_13, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_4, ID.ID_13, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_4, ID.ID_13, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_4, ID.ID_14, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_4, ID.ID_14, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_4, ID.ID_14, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_4, ID.ID_14, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_4, ID.ID_30, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_4, ID.ID_30, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_4, ID.ID_30, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_4, ID.ID_30, CameraType.VIS),
                                       FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_5, ID.ID_31, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_5, ID.ID_31, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_5, ID.ID_31, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_5, ID.ID_31, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_5, ID.ID_32, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_5, ID.ID_32, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_5, ID.ID_32, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_5, ID.ID_32, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_5, ID.ID_33, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_5, ID.ID_33, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_5, ID.ID_33, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_5, ID.ID_33, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_5, ID.ID_34, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_5, ID.ID_34, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_5, ID.ID_34, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_5, ID.ID_34, CameraType.VIS),
                                       FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_6, ID.ID_3, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_6, ID.ID_3, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_6, ID.ID_3, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_6, ID.ID_3, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_6, ID.ID_5, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_6, ID.ID_5, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_6, ID.ID_5, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_6, ID.ID_5, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_6, ID.ID_9, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_6, ID.ID_9, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_6, ID.ID_9, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_6, ID.ID_9, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_6, ID.ID_25, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_6, ID.ID_25, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_6, ID.ID_25, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_6, ID.ID_25, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_6, ID.ID_27, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_6, ID.ID_27, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_6, ID.ID_27, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_6, ID.ID_27, CameraType.VIS),
                                       FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_7, ID.ID_1, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_7, ID.ID_1, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_7, ID.ID_1, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_7, ID.ID_1, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_7, ID.ID_12, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_7, ID.ID_12, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_7, ID.ID_12, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_7, ID.ID_12, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_7, ID.ID_19, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_7, ID.ID_19, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_7, ID.ID_19, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_7, ID.ID_19, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_7, ID.ID_24, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_7, ID.ID_24, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_7, ID.ID_24, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_7, ID.ID_24, CameraType.VIS),
                                       FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_8, ID.ID_10, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_8, ID.ID_10, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_8, ID.ID_10, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_8, ID.ID_10, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_8, ID.ID_11, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_8, ID.ID_11, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_8, ID.ID_11, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_8, ID.ID_11, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_8, ID.ID_16, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_8, ID.ID_16, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_8, ID.ID_16, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_8, ID.ID_16, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_8, ID.ID_26, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_8, ID.ID_26, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_8, ID.ID_26, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_8, ID.ID_26, CameraType.VIS),
                                       FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_9, ID.ID_4, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_9, ID.ID_4, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_9, ID.ID_4, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_9, ID.ID_4, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_9, ID.ID_15, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_9, ID.ID_15, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_9, ID.ID_15, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_9, ID.ID_15, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_9, ID.ID_20, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_9, ID.ID_20, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_9, ID.ID_20, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_9, ID.ID_20, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_9, ID.ID_21, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.FRONT, Day.DAY_M4_9, ID.ID_21, CameraType.VIS),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_9, ID.ID_21, CameraType.VIS_COR),
                     FruitRecord(Fruit.AVOCADO, Side.BACK, Day.DAY_M4_9, ID.ID_21, CameraType.VIS)]
